### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by Paalar** [dotkom/onlineweb-frontend#146]
The beta version has no favicon.
Sorry for the low res images.

Beta:
<img width="90" alt="screenshot 2018-11-24 at 15 47 41" src="https://user-images.githubusercontent.com/22390745/48969557-95e0bd00-f000-11e8-98da-a31bbcb5041f.png">

OW4:
<img width="164" alt="screenshot 2018-11-24 at 15 47 48" src="https://user-images.githubusercontent.com/22390745/48969549-7d70a280-f000-11e8-85ac-766c02a453e4.png">

Something extra:
Would be cool to implement a loading favicon, much like the rotating svgs.
<img width="129" alt="screenshot 2018-11-24 at 15 48 02" src="https://user-images.githubusercontent.com/22390745/48969544-79dd1b80-f000-11e8-88e6-9d57bf2b39dd.png">

**Comment by oleast** [comment]
I have tested out a few solutions for this, but I have not implemented any yet, because we will end up changing how the initial HTML is loaded in #84 

This is the current I was thinking of going for:

<img width="180" alt="owf-online-logo" src="https://user-images.githubusercontent.com/14319313/48969647-b0fffc80-f001-11e8-86fa-321c952b229a.png">

It is just a filled out spinner with a lot of the complicated things removed.
Last time I read about it, an actual spinning icon would not be possible 😞
