### ISSUE TITLE
Event card not appearing in ImageView

### ISSUE THREAD

**Issue by henrikhorluck** [dotkom/onlineweb-frontend#245]
**Describe the bug**

The event card for "Eksamensforelesning - Databse" does not appear on the front page

**To Reproduce**
1. Go to beta.online.ntnu.no
2. Observe missing event card

**Expected behavior**

The event card appears

**Screenshots**
<img width="1143" alt="Screenshot 2019-04-30 at 12 17 56" src="https://user-images.githubusercontent.com/36937807/56955736-7ebf7180-6b42-11e9-902b-6de8041b7994.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: newest

**Additional context**
The event that doesn't appear is https://beta.online.ntnu.no/events/702
width > 1024px

**Comment by mariush2** [comment]
Get the exact same bug on Windows 10 desktop.

**Comment by oleast** [comment]
There is no event that does not appear. The vent you specified is right there, at the top.

The problem here is how the grid handles varying amounts of events. This was previously fixed by adding emtpy block. Could be fixed here by using `flex` instead of `grid`.

![eventviews](https://user-images.githubusercontent.com/14319313/56958850-d6aea600-6b4b-11e9-8e1f-560732299fba.png)
