### ISSUE TITLE
Event detail does not fetch event data

### ISSUE THREAD

**Issue by tokongs** [dotkom/onlineweb-frontend#281]
**Describe the bug**
If you click an event when not logged in everything is fine. But when you try to log in while already on the event page no event info is rendered.

**To Reproduce**
1. Go to beta.online.ntnu.no
2. Click on an event
3. Click on login
4. ???
5. profit

**Expected behavior**
The event should show up correctly as it does when you refresh the page.

**Screenshots**
![bug](https://user-images.githubusercontent.com/6499473/63753915-45aaca00-c8b4-11e9-99e7-f866530cb589.png)

**Desktop (please complete the following information):**
 - OS: Linux 4.19.66-1-MANJARO
 - Browser: Chrome 
 - Version: 76

**Comment by oleast** [comment]
So this is not actually a problem with logging in, it is a problem with the event detail view not actually fetching the event data at all.
This worked mostly well when an event was already fetched by either the front-page or by SSR, but not when transitioning to the page without loading the data beforehand.

Logging in caused a refresh of the entire app (because signInRedirect), which cleared the state of all events. Then it redirected you to the page you were on, which in this case was the event detail, but without any event previously stored to get from.

Now that the SSR things have been reset, and are continually re-introduced this problem will also appear any time you try to load an event page without going to the front-page an clicking on a link to it.

**Comment by FluidSense** [comment]
@oleast 
I see, great clarification!
Could this perhaps be solved by triggering a thunkaction, requesting the event if it is not present?
And perhaps adding a loading spinner if the event data is missing and it is being fetched?
Perhaps also redirecting to a 404-page if the event-ID is unknown, in case someone goes directly by URL (which also triggers this error)

**Comment by oleast** [comment]
@FluidSense 
That would be exactly the solution I would go for :smile: 
I think the way it is done in the Articles example from #343 would work just as well here?
