### ISSUE TITLE
Router doesn't handle absolute event url's generated by the REST api.

### ISSUE THREAD

**Issue by petterroea** [dotkom/onlineweb-frontend#394]
**Describe the bug**  

The REST api generates absolute URL's in this form: `/events/972/hoyt-og-lavt-fadderbarn/`

Appending the absolute url to `https://online.ntnu.no` gives a 404 page. However, removing the last directory of the absolute url provides a valid URL. For example, `/events/972/` is a valid URL.

**To Reproduce**
1. Go to https://online.ntnu.no/api/v1/events/
2. Find an `absolute_url` value. Append it to `https://online.ntnu.no`
3. Try to visit the result of the previous step in your web browser, observe the 404
4. Remove the last directory from the generated url, visit it in your web browser, observe that it works now.

**Expected behavior**
I expect the `absolute_url` field to show me the event i am trying to view.

**Desktop (please complete the following information):**
 - OS: `x86_64 Linux 5.8.7-arch1-1`
 - Browser: Firefox
 - Version: `80.0.1 (64-bit)`

**Comment by FluidSense** [comment]
This is caused by the [Onlineweb4-event model](https://github.com/dotkom/onlineweb4/blob/3e11868ffba7a87d054123bfdf1e0633870d288f/apps/events/models/Event.py#L100) and the corresponding [serializer](https://github.com/dotkom/onlineweb4/blob/3e11868ffba7a87d054123bfdf1e0633870d288f/apps/events/serializers.py#L61) which structures the URLs in the format that Django uses and not how the new frontend likes them. 
```python
    absolute_url = serializers.CharField(source="get_absolute_url", read_only=True)

    [...]

    def get_absolute_url(self):
        return reverse(
            "events_details", kwargs={"event_id": self.id, "event_slug": self.slug}
        )
```
I'm not certain about what would be the best way to handle this, in the API or in the frontend.
Perhaps Next can be configured to allow for the titles to be ignored when hitting the `events/[eventId]` path, or the API can be configured to return the value without the title. The last option could end up breaking things at old.online.ntnu.no if something there relies on the django-based URL from the API. However, it would perhaps be more correct to change it to the format that OWF uses as it is what is running on the domain `online.ntnu.no` which the url corresponds to.

**Comment by FluidSense** [comment]
I think the easiest fix is to allow for the `absolute_url`s from Django for now, to ensure that all functionality still exists.
Events can have a [catch-all](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes) for such routes.
