### ISSUE TITLE
Reimplement the footer

### ISSUE THREAD

**Issue by sardred** [dotkom/onlineweb-frontend#69]
With Bootstrap gone, we have a great chance to take another look at the footer. We don't have any icons anymore (#63), as of right now there's no map, text is super tiny and low-contrast.
Also, not sure if google+ is any relevant to link to anymore :upside_down_face: 
Whoever takes on the issue is free to redesign the footer completely!

**Comment by henrikhorluck** [comment]
Okay so thinking about this, and I would like to see: darker color, something like a "about Online"/"Om"/"Om Online", where we can place _something_ akin to the [chunks](https://online.ntnu.no/#!about/online) on our current homepage, and a "Contact"/"Find us", which leads to a page where we can have all the addresses, contact info and "kvitteringskjema" etc. And of course something that links to either dotkom@onn or this repo itself. I would like if it was more like one line of text, instead of the huge chunk it is today, but that is just my opinion. And of course, the logo of our general sponsor in the middle.

**Comment by oleast** [comment]
I like the idea, and think we should simplify the footer a bit.

### Chunks
When it comes to chunks, that will be the domain for `Fuzzy Train`, as we want to move as much as possible of that relevant information closer to first-time users.
Contact @Westermoen for more about that. 

Could probably put a little sentence in there or something, but it feels a bit symbolic.

### Sponsor
For the sponsor I would also like to put the logo in the footer instead of the header. That is _again_ something that has to be discussed with Bedkom, and agreed upon by the sponsor.

I think it would be nice to free up the space in the header, for other uses :smile: 

### Other projects
Nice idea, but I think we have too many other projects to put them in the footer.

My idea here is to completely rethink how we display other projects as a whole:
https://github.com/dotkom/onlineweb-frontend/issues/226
